using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Terraria_Server
{
    public enum ProjectileType
    {
        UNKNOWN,
        ARROW_WOODEN,
        ARROW_FIRE,
        SHURIKEN,
        ARROW_UNHOLY,
        ARROW_JESTER,
        BOOMERANG_ENCHANTED,
        VILETHORN,
        VILETHORN_B,
        STARFURY,
        POWDER_PURIFICATION,
        POWDER_VILE,
        FALLEN_STAR,
        HOOK,
        BALL_MUSKET,
        BALL_OF_FIRE,
        MISSILE_MAGIC,
        BALL_DIRT,
        ORB_OF_LIGHT,
        FLAMARANG,
        LASER_GREEN,
        BONE,
        STREAM_WATER,
        HARPOON,
        BALL_SPIKY,
        BALL_O_HURT,
        BLUE_MOON,
        BOLT_WATER,
        BOMB,
        DYNAMITE,
        GRENADE,
        BALL_SAND_DROP,
        WHIP_IVY,
        CHAKRUM_THORN,
        FLAMELASH,
        SUNFURY,
        SHOT_METEOR,
        BOMB_STICKY,
        FEATHER_HARPY,
        BALL_MUD,
        BALL_ASH,
        ARROW_HELLFIRE,
        BALL_SAND_GUN,
        TOMBSTONE,
        SICKLE_DEMON,
        SCYTHE_DEMON,
        LANCE_DARK,
        TRIDENT,
        KNIFE_THROWING,
        SPEAR,
        GLOWSTICK,
        SEED,
        BOOMERANG_WOODEN,
        GLOWSTICK_STICKY,
        KNIFE_POISONED
    }
}
