using System;

namespace Terraria_Server
{
	public class Recipe
	{
		public static int maxRequirements = 10;
		public static int maxRecipes = 200;
		public static int numRecipes = 0;
		private static Recipe newRecipe = new Recipe();
		public Item createItem = new Item();
		public Item[] requiredItem = new Item[Recipe.maxRequirements];
		public int[] requiredTile = new int[Recipe.maxRequirements];

		public Recipe()
		{
			for (int i = 0; i < Recipe.maxRequirements; i++)
			{
				this.requiredItem[i] = new Item();
				this.requiredTile[i] = -1;
			}
		}

		public void Create()
		{
			int num = 0;
			while (num < Recipe.maxRequirements && this.requiredItem[num].Type != 0)
			{
				int num2 = this.requiredItem[num].Stack;
				for (int i = 0; i < 44; i++)
				{
					if (Main.players[Main.myPlayer].inventory[i].IsTheSameAs(this.requiredItem[num]))
					{
						if (Main.players[Main.myPlayer].inventory[i].Stack > num2)
						{
							Main.players[Main.myPlayer].inventory[i].Stack -= num2;
							num2 = 0;
						}
						else
						{
							num2 -= Main.players[Main.myPlayer].inventory[i].Stack;
							Main.players[Main.myPlayer].inventory[i] = new Item();
						}
					}
					if (num2 <= 0)
					{
						break;
					}
				}
				num++;
			}
			Recipe.FindRecipes();
		}

		public static void FindRecipes()
		{
			int num = Main.availableRecipe[Main.focusRecipe];
			float num2 = Main.availableRecipeY[Main.focusRecipe];
			for (int i = 0; i < Recipe.maxRecipes; i++)
			{
				Main.availableRecipe[i] = 0;
			}
			Main.numAvailableRecipes = 0;
			int num3 = 0;
			while (num3 < Recipe.maxRecipes && Main.recipe[num3].createItem.Type != 0)
			{
				bool flag = true;
				int num4 = 0;
				while (num4 < Recipe.maxRequirements && Main.recipe[num3].requiredItem[num4].Type != 0)
				{
					int num5 = Main.recipe[num3].requiredItem[num4].Stack;
					for (int j = 0; j < 44; j++)
					{
						if (Main.players[Main.myPlayer].inventory[j].IsTheSameAs(Main.recipe[num3].requiredItem[num4]))
						{
							num5 -= Main.players[Main.myPlayer].inventory[j].Stack;
						}
						if (num5 <= 0)
						{
							break;
						}
					}
					if (num5 > 0)
					{
						flag = false;
						break;
					}
					num4++;
				}
				if (flag)
				{
					bool flag2 = true;
					int num6 = 0;
					while (num6 < Recipe.maxRequirements && Main.recipe[num3].requiredTile[num6] != -1)
					{
						if (!Main.players[Main.myPlayer].adjTile[Main.recipe[num3].requiredTile[num6]])
						{
							flag2 = false;
							break;
						}
						num6++;
					}
					if (flag2)
					{
						Main.availableRecipe[Main.numAvailableRecipes] = num3;
						Main.numAvailableRecipes++;
					}
				}
				num3++;
			}
			for (int k = 0; k < Main.numAvailableRecipes; k++)
			{
				if (num == Main.availableRecipe[k])
				{
					Main.focusRecipe = k;
					break;
				}
			}
			if (Main.focusRecipe >= Main.numAvailableRecipes)
			{
				Main.focusRecipe = Main.numAvailableRecipes - 1;
			}
			if (Main.focusRecipe < 0)
			{
				Main.focusRecipe = 0;
			}
			float num7 = Main.availableRecipeY[Main.focusRecipe] - num2;
			for (int l = 0; l < Recipe.maxRecipes; l++)
			{
				Main.availableRecipeY[l] -= num7;
			}
		}

		public static void SetupRecipes()
		{
            Recipe.numRecipes = 0;
			Recipe.newRecipe.createItem.SetDefaults(28);
			Recipe.newRecipe.createItem.Stack = 2;
			Recipe.newRecipe.requiredItem[0].SetDefaults(5);
			Recipe.newRecipe.requiredItem[1].SetDefaults(23);
			Recipe.newRecipe.requiredItem[1].Stack = 2;
			Recipe.newRecipe.requiredItem[2].SetDefaults(31);
			Recipe.newRecipe.requiredItem[2].Stack = 2;
			Recipe.newRecipe.requiredTile[0] = 13;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Healing Potion");
			Recipe.newRecipe.requiredItem[0].SetDefaults(28);
			Recipe.newRecipe.requiredItem[0].Stack = 2;
			Recipe.newRecipe.requiredItem[1].SetDefaults(183);
			Recipe.newRecipe.requiredTile[0] = 13;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(110);
			Recipe.newRecipe.createItem.Stack = 2;
			Recipe.newRecipe.requiredItem[0].SetDefaults(75);
			Recipe.newRecipe.requiredItem[1].SetDefaults(23);
			Recipe.newRecipe.requiredItem[1].Stack = 2;
			Recipe.newRecipe.requiredItem[2].SetDefaults(31);
			Recipe.newRecipe.requiredItem[2].Stack = 2;
			Recipe.newRecipe.requiredTile[0] = 13;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Mana Potion");
			Recipe.newRecipe.requiredItem[0].SetDefaults(110);
			Recipe.newRecipe.requiredItem[0].Stack = 2;
			Recipe.newRecipe.requiredItem[1].SetDefaults(183);
			Recipe.newRecipe.requiredTile[0] = 13;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(226);
			Recipe.newRecipe.requiredItem[0].SetDefaults(28);
			Recipe.newRecipe.requiredItem[1].SetDefaults(110);
			Recipe.newRecipe.requiredTile[0] = 13;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(227);
			Recipe.newRecipe.requiredItem[0].SetDefaults("Healing Potion");
			Recipe.newRecipe.requiredItem[1].SetDefaults("Mana Potion");
			Recipe.newRecipe.requiredTile[0] = 13;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(67);
			Recipe.newRecipe.createItem.Stack = 5;
			Recipe.newRecipe.requiredItem[0].SetDefaults(60);
			Recipe.newRecipe.requiredTile[0] = 13;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Bottle");
			Recipe.newRecipe.createItem.Stack = 2;
			Recipe.newRecipe.requiredItem[0].SetDefaults("Glass");
			Recipe.newRecipe.requiredTile[0] = 17;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(8);
			Recipe.newRecipe.createItem.Stack = 3;
			Recipe.newRecipe.requiredItem[0].SetDefaults(23);
			Recipe.newRecipe.requiredItem[0].Stack = 1;
			Recipe.newRecipe.requiredItem[1].SetDefaults(9);
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(235);
			Recipe.newRecipe.requiredItem[0].SetDefaults(166);
			Recipe.newRecipe.requiredItem[1].SetDefaults(23);
			Recipe.newRecipe.requiredItem[1].Stack = 5;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Glass");
			Recipe.newRecipe.createItem.Stack = 1;
			Recipe.newRecipe.requiredItem[0].SetDefaults(169);
			Recipe.newRecipe.requiredItem[0].Stack = 2;
			Recipe.newRecipe.requiredTile[0] = 17;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Clay Pot");
			Recipe.newRecipe.requiredItem[0].SetDefaults(133);
			Recipe.newRecipe.requiredItem[0].Stack = 6;
			Recipe.newRecipe.requiredTile[0] = 17;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Gray Brick");
			Recipe.newRecipe.requiredItem[0].SetDefaults(3);
			Recipe.newRecipe.requiredItem[0].Stack = 2;
			Recipe.newRecipe.requiredTile[0] = 17;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Gray Brick Wall");
			Recipe.newRecipe.createItem.Stack = 4;
			Recipe.newRecipe.requiredItem[0].SetDefaults("Gray Brick");
			Recipe.newRecipe.requiredTile[0] = 18;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Red Brick");
			Recipe.newRecipe.requiredItem[0].SetDefaults(133);
			Recipe.newRecipe.requiredItem[0].Stack = 2;
			Recipe.newRecipe.requiredTile[0] = 17;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Red Brick Wall");
			Recipe.newRecipe.createItem.Stack = 4;
			Recipe.newRecipe.requiredItem[0].SetDefaults("Red Brick");
			Recipe.newRecipe.requiredTile[0] = 18;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Copper Brick");
			Recipe.newRecipe.requiredItem[0].SetDefaults(3);
			Recipe.newRecipe.requiredItem[0].Stack = 1;
			Recipe.newRecipe.requiredItem[1].SetDefaults("Copper Ore");
			Recipe.newRecipe.requiredItem[1].Stack = 1;
			Recipe.newRecipe.requiredTile[0] = 17;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Copper Brick Wall");
			Recipe.newRecipe.createItem.Stack = 4;
			Recipe.newRecipe.requiredItem[0].SetDefaults("Copper Brick");
			Recipe.newRecipe.requiredTile[0] = 18;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Silver Brick Wall");
			Recipe.newRecipe.createItem.Stack = 4;
			Recipe.newRecipe.requiredItem[0].SetDefaults("Silver Brick");
			Recipe.newRecipe.requiredTile[0] = 18;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Silver Brick");
			Recipe.newRecipe.requiredItem[0].SetDefaults(3);
			Recipe.newRecipe.requiredItem[0].Stack = 1;
			Recipe.newRecipe.requiredItem[1].SetDefaults("Silver Ore");
			Recipe.newRecipe.requiredItem[1].Stack = 1;
			Recipe.newRecipe.requiredTile[0] = 17;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Gold Brick Wall");
			Recipe.newRecipe.createItem.Stack = 4;
			Recipe.newRecipe.requiredItem[0].SetDefaults("Gold Brick");
			Recipe.newRecipe.requiredTile[0] = 18;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Gold Brick");
			Recipe.newRecipe.requiredItem[0].SetDefaults(3);
			Recipe.newRecipe.requiredItem[0].Stack = 1;
			Recipe.newRecipe.requiredItem[1].SetDefaults("Gold Ore");
			Recipe.newRecipe.requiredItem[1].Stack = 1;
			Recipe.newRecipe.requiredTile[0] = 17;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Hellstone Brick");
			Recipe.newRecipe.requiredItem[0].SetDefaults(174);
			Recipe.newRecipe.requiredItem[1].SetDefaults(1);
			Recipe.newRecipe.requiredTile[0] = 17;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(192);
			Recipe.newRecipe.requiredItem[0].SetDefaults(173);
			Recipe.newRecipe.requiredItem[0].Stack = 2;
			Recipe.newRecipe.requiredTile[0] = 17;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(30);
			Recipe.newRecipe.createItem.Stack = 4;
			Recipe.newRecipe.requiredItem[0].SetDefaults(2);
			Recipe.newRecipe.requiredTile[0] = 18;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(26);
			Recipe.newRecipe.createItem.Stack = 4;
			Recipe.newRecipe.requiredItem[0].SetDefaults(3);
			Recipe.newRecipe.requiredTile[0] = 18;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(93);
			Recipe.newRecipe.createItem.Stack = 4;
			Recipe.newRecipe.requiredItem[0].SetDefaults(9);
			Recipe.newRecipe.requiredTile[0] = 18;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(94);
			Recipe.newRecipe.requiredItem[0].SetDefaults(9);
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(25);
			Recipe.newRecipe.requiredItem[0].SetDefaults(9);
			Recipe.newRecipe.requiredItem[0].Stack = 6;
			Recipe.newRecipe.requiredTile[0] = 18;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(34);
			Recipe.newRecipe.requiredItem[0].SetDefaults(9);
			Recipe.newRecipe.requiredItem[0].Stack = 4;
			Recipe.newRecipe.requiredTile[0] = 18;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Sign");
			Recipe.newRecipe.requiredItem[0].SetDefaults(9);
			Recipe.newRecipe.requiredItem[0].Stack = 6;
			Recipe.newRecipe.requiredTile[0] = 18;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(48);
			Recipe.newRecipe.requiredItem[0].SetDefaults(9);
			Recipe.newRecipe.requiredItem[0].Stack = 8;
			Recipe.newRecipe.requiredItem[1].SetDefaults(22);
			Recipe.newRecipe.requiredItem[1].Stack = 2;
			Recipe.newRecipe.requiredTile[0] = 18;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(32);
			Recipe.newRecipe.requiredItem[0].SetDefaults(9);
			Recipe.newRecipe.requiredItem[0].Stack = 8;
			Recipe.newRecipe.requiredTile[0] = 18;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(36);
			Recipe.newRecipe.requiredItem[0].SetDefaults(9);
			Recipe.newRecipe.requiredItem[0].Stack = 10;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(24);
			Recipe.newRecipe.requiredItem[0].SetDefaults(9);
			Recipe.newRecipe.requiredItem[0].Stack = 7;
			Recipe.newRecipe.requiredTile[0] = 18;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(196);
			Recipe.newRecipe.requiredItem[0].SetDefaults(9);
			Recipe.newRecipe.requiredItem[0].Stack = 8;
			Recipe.newRecipe.requiredTile[0] = 18;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(40);
			Recipe.newRecipe.createItem.Stack = 3;
			Recipe.newRecipe.requiredItem[0].SetDefaults(9);
			Recipe.newRecipe.requiredItem[1].SetDefaults(3);
			Recipe.newRecipe.requiredTile[0] = 18;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(39);
			Recipe.newRecipe.requiredItem[0].SetDefaults(9);
			Recipe.newRecipe.requiredItem[0].Stack = 10;
			Recipe.newRecipe.requiredTile[0] = 18;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Bed");
			Recipe.newRecipe.requiredItem[0].SetDefaults(9);
			Recipe.newRecipe.requiredItem[0].Stack = 15;
			Recipe.newRecipe.requiredItem[1].SetDefaults("Silk");
			Recipe.newRecipe.requiredItem[1].Stack = 5;
			Recipe.newRecipe.requiredTile[0] = 18;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Silk");
			Recipe.newRecipe.requiredItem[0].SetDefaults(150);
			Recipe.newRecipe.requiredItem[0].Stack = 10;
			Recipe.newRecipe.requiredTile[0] = 18;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Flaming Arrow");
			Recipe.newRecipe.createItem.Stack = 5;
			Recipe.newRecipe.requiredItem[0].SetDefaults(40);
			Recipe.newRecipe.requiredItem[0].Stack = 5;
			Recipe.newRecipe.requiredItem[1].SetDefaults(8);
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(33);
			Recipe.newRecipe.requiredItem[0].SetDefaults(3);
			Recipe.newRecipe.requiredItem[0].Stack = 20;
			Recipe.newRecipe.requiredItem[1].SetDefaults(9);
			Recipe.newRecipe.requiredItem[1].Stack = 4;
			Recipe.newRecipe.requiredItem[2].SetDefaults(8);
			Recipe.newRecipe.requiredItem[2].Stack = 3;
			Recipe.newRecipe.requiredTile[0] = 18;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(20);
			Recipe.newRecipe.requiredItem[0].SetDefaults(12);
			Recipe.newRecipe.requiredItem[0].Stack = 3;
			Recipe.newRecipe.requiredTile[0] = 17;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Copper Pickaxe");
			Recipe.newRecipe.requiredItem[0].SetDefaults(20);
			Recipe.newRecipe.requiredItem[0].Stack = 12;
			Recipe.newRecipe.requiredItem[1].SetDefaults(9);
			Recipe.newRecipe.requiredItem[1].Stack = 4;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Copper Axe");
			Recipe.newRecipe.requiredItem[0].SetDefaults(20);
			Recipe.newRecipe.requiredItem[0].Stack = 9;
			Recipe.newRecipe.requiredItem[1].SetDefaults(9);
			Recipe.newRecipe.requiredItem[1].Stack = 3;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Copper Hammer");
			Recipe.newRecipe.requiredItem[0].SetDefaults(20);
			Recipe.newRecipe.requiredItem[0].Stack = 10;
			Recipe.newRecipe.requiredItem[1].SetDefaults(9);
			Recipe.newRecipe.requiredItem[1].Stack = 3;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Copper Broadsword");
			Recipe.newRecipe.requiredItem[0].SetDefaults(20);
			Recipe.newRecipe.requiredItem[0].Stack = 8;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Copper Shortsword");
			Recipe.newRecipe.requiredItem[0].SetDefaults(20);
			Recipe.newRecipe.requiredItem[0].Stack = 7;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Copper Bow");
			Recipe.newRecipe.requiredItem[0].SetDefaults(20);
			Recipe.newRecipe.requiredItem[0].Stack = 7;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Copper Helmet");
			Recipe.newRecipe.requiredItem[0].SetDefaults(20);
			Recipe.newRecipe.requiredItem[0].Stack = 15;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Copper Chainmail");
			Recipe.newRecipe.requiredItem[0].SetDefaults(20);
			Recipe.newRecipe.requiredItem[0].Stack = 25;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Copper Greaves");
			Recipe.newRecipe.requiredItem[0].SetDefaults(20);
			Recipe.newRecipe.requiredItem[0].Stack = 20;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Copper Watch");
			Recipe.newRecipe.requiredItem[0].SetDefaults(20);
			Recipe.newRecipe.requiredItem[0].Stack = 10;
			Recipe.newRecipe.requiredItem[1].SetDefaults(85);
			Recipe.newRecipe.requiredTile[0] = 14;
			Recipe.newRecipe.requiredTile[1] = 15;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Copper Chandelier");
			Recipe.newRecipe.requiredItem[0].SetDefaults(20);
			Recipe.newRecipe.requiredItem[0].Stack = 4;
			Recipe.newRecipe.requiredItem[1].SetDefaults(8);
			Recipe.newRecipe.requiredItem[1].Stack = 4;
			Recipe.newRecipe.requiredItem[2].SetDefaults(85);
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(22);
			Recipe.newRecipe.requiredItem[0].SetDefaults(11);
			Recipe.newRecipe.requiredItem[0].Stack = 3;
			Recipe.newRecipe.requiredTile[0] = 17;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(35);
			Recipe.newRecipe.requiredItem[0].SetDefaults(22);
			Recipe.newRecipe.requiredItem[0].Stack = 5;
			Recipe.newRecipe.requiredTile[0] = 18;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(205);
			Recipe.newRecipe.requiredItem[0].SetDefaults(22);
			Recipe.newRecipe.requiredItem[0].Stack = 3;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(1);
			Recipe.newRecipe.requiredItem[0].SetDefaults(22);
			Recipe.newRecipe.requiredItem[0].Stack = 12;
			Recipe.newRecipe.requiredItem[1].SetDefaults(9);
			Recipe.newRecipe.requiredItem[1].Stack = 3;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(10);
			Recipe.newRecipe.requiredItem[0].SetDefaults(22);
			Recipe.newRecipe.requiredItem[0].Stack = 9;
			Recipe.newRecipe.requiredItem[1].SetDefaults(9);
			Recipe.newRecipe.requiredItem[1].Stack = 3;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(7);
			Recipe.newRecipe.requiredItem[0].SetDefaults(22);
			Recipe.newRecipe.requiredItem[0].Stack = 10;
			Recipe.newRecipe.requiredItem[1].SetDefaults(9);
			Recipe.newRecipe.requiredItem[1].Stack = 3;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(4);
			Recipe.newRecipe.requiredItem[0].SetDefaults(22);
			Recipe.newRecipe.requiredItem[0].Stack = 8;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(6);
			Recipe.newRecipe.requiredItem[0].SetDefaults(22);
			Recipe.newRecipe.requiredItem[0].Stack = 7;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Iron Bow");
			Recipe.newRecipe.requiredItem[0].SetDefaults(22);
			Recipe.newRecipe.requiredItem[0].Stack = 7;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Iron Helmet");
			Recipe.newRecipe.requiredItem[0].SetDefaults(22);
			Recipe.newRecipe.requiredItem[0].Stack = 20;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Iron Chainmail");
			Recipe.newRecipe.requiredItem[0].SetDefaults(22);
			Recipe.newRecipe.requiredItem[0].Stack = 30;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Iron Greaves");
			Recipe.newRecipe.requiredItem[0].SetDefaults(22);
			Recipe.newRecipe.requiredItem[0].Stack = 25;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Iron Chain");
			Recipe.newRecipe.requiredItem[0].SetDefaults(22);
			Recipe.newRecipe.requiredItem[0].Stack = 3;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(21);
			Recipe.newRecipe.requiredItem[0].SetDefaults(14);
			Recipe.newRecipe.requiredItem[0].Stack = 4;
			Recipe.newRecipe.requiredTile[0] = 17;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Silver Pickaxe");
			Recipe.newRecipe.requiredItem[0].SetDefaults(21);
			Recipe.newRecipe.requiredItem[0].Stack = 12;
			Recipe.newRecipe.requiredItem[1].SetDefaults(9);
			Recipe.newRecipe.requiredItem[1].Stack = 4;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Silver Axe");
			Recipe.newRecipe.requiredItem[0].SetDefaults(21);
			Recipe.newRecipe.requiredItem[0].Stack = 9;
			Recipe.newRecipe.requiredItem[1].SetDefaults(9);
			Recipe.newRecipe.requiredItem[1].Stack = 3;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Silver Hammer");
			Recipe.newRecipe.requiredItem[0].SetDefaults(21);
			Recipe.newRecipe.requiredItem[0].Stack = 10;
			Recipe.newRecipe.requiredItem[1].SetDefaults(9);
			Recipe.newRecipe.requiredItem[1].Stack = 3;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Silver Broadsword");
			Recipe.newRecipe.requiredItem[0].SetDefaults(21);
			Recipe.newRecipe.requiredItem[0].Stack = 8;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Silver Bow");
			Recipe.newRecipe.requiredItem[0].SetDefaults(21);
			Recipe.newRecipe.requiredItem[0].Stack = 7;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Silver Helmet");
			Recipe.newRecipe.requiredItem[0].SetDefaults(21);
			Recipe.newRecipe.requiredItem[0].Stack = 20;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Silver Chainmail");
			Recipe.newRecipe.requiredItem[0].SetDefaults(21);
			Recipe.newRecipe.requiredItem[0].Stack = 30;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Silver Greaves");
			Recipe.newRecipe.requiredItem[0].SetDefaults(21);
			Recipe.newRecipe.requiredItem[0].Stack = 25;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Silver Watch");
			Recipe.newRecipe.requiredItem[0].SetDefaults(21);
			Recipe.newRecipe.requiredItem[0].Stack = 10;
			Recipe.newRecipe.requiredItem[1].SetDefaults(85);
			Recipe.newRecipe.requiredTile[0] = 14;
			Recipe.newRecipe.requiredTile[1] = 15;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Silver Chandelier");
			Recipe.newRecipe.requiredItem[0].SetDefaults(21);
			Recipe.newRecipe.requiredItem[0].Stack = 4;
			Recipe.newRecipe.requiredItem[1].SetDefaults(8);
			Recipe.newRecipe.requiredItem[1].Stack = 4;
			Recipe.newRecipe.requiredItem[2].SetDefaults(85);
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(19);
			Recipe.newRecipe.requiredItem[0].SetDefaults(13);
			Recipe.newRecipe.requiredItem[0].Stack = 4;
			Recipe.newRecipe.requiredTile[0] = 17;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Gold Pickaxe");
			Recipe.newRecipe.requiredItem[0].SetDefaults(19);
			Recipe.newRecipe.requiredItem[0].Stack = 12;
			Recipe.newRecipe.requiredItem[1].SetDefaults(9);
			Recipe.newRecipe.requiredItem[1].Stack = 4;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Gold Axe");
			Recipe.newRecipe.requiredItem[0].SetDefaults(19);
			Recipe.newRecipe.requiredItem[0].Stack = 9;
			Recipe.newRecipe.requiredItem[1].SetDefaults(9);
			Recipe.newRecipe.requiredItem[1].Stack = 3;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Gold Hammer");
			Recipe.newRecipe.requiredItem[0].SetDefaults(19);
			Recipe.newRecipe.requiredItem[0].Stack = 10;
			Recipe.newRecipe.requiredItem[1].SetDefaults(9);
			Recipe.newRecipe.requiredItem[1].Stack = 3;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Gold Broadsword");
			Recipe.newRecipe.requiredItem[0].SetDefaults(19);
			Recipe.newRecipe.requiredItem[0].Stack = 8;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Gold Shortsword");
			Recipe.newRecipe.requiredItem[0].SetDefaults(19);
			Recipe.newRecipe.requiredItem[0].Stack = 7;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Gold Bow");
			Recipe.newRecipe.requiredItem[0].SetDefaults(19);
			Recipe.newRecipe.requiredItem[0].Stack = 7;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Gold Helmet");
			Recipe.newRecipe.requiredItem[0].SetDefaults(19);
			Recipe.newRecipe.requiredItem[0].Stack = 25;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Gold Chainmail");
			Recipe.newRecipe.requiredItem[0].SetDefaults(19);
			Recipe.newRecipe.requiredItem[0].Stack = 35;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Gold Greaves");
			Recipe.newRecipe.requiredItem[0].SetDefaults(19);
			Recipe.newRecipe.requiredItem[0].Stack = 30;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Gold Watch");
			Recipe.newRecipe.requiredItem[0].SetDefaults(19);
			Recipe.newRecipe.requiredItem[0].Stack = 10;
			Recipe.newRecipe.requiredItem[1].SetDefaults(85);
			Recipe.newRecipe.requiredTile[0] = 14;
			Recipe.newRecipe.requiredTile[1] = 15;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Gold Chandelier");
			Recipe.newRecipe.requiredItem[0].SetDefaults(19);
			Recipe.newRecipe.requiredItem[0].Stack = 4;
			Recipe.newRecipe.requiredItem[1].SetDefaults(8);
			Recipe.newRecipe.requiredItem[1].Stack = 4;
			Recipe.newRecipe.requiredItem[2].SetDefaults(85);
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Candle");
			Recipe.newRecipe.requiredItem[0].SetDefaults(19);
			Recipe.newRecipe.requiredItem[1].SetDefaults(8);
			Recipe.newRecipe.requiredTile[0] = 18;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(57);
			Recipe.newRecipe.requiredItem[0].SetDefaults(56);
			Recipe.newRecipe.requiredItem[0].Stack = 4;
			Recipe.newRecipe.requiredTile[0] = 17;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(44);
			Recipe.newRecipe.requiredItem[0].SetDefaults(57);
			Recipe.newRecipe.requiredItem[0].Stack = 8;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Unholy Arrow");
			Recipe.newRecipe.createItem.Stack = 2;
			Recipe.newRecipe.requiredItem[0].SetDefaults(40);
			Recipe.newRecipe.requiredItem[0].Stack = 2;
			Recipe.newRecipe.requiredItem[1].SetDefaults(69);
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(45);
			Recipe.newRecipe.requiredItem[0].SetDefaults(57);
			Recipe.newRecipe.requiredItem[0].Stack = 10;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(46);
			Recipe.newRecipe.requiredItem[0].SetDefaults(57);
			Recipe.newRecipe.requiredItem[0].Stack = 10;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Shadow Helmet");
			Recipe.newRecipe.requiredItem[0].SetDefaults(57);
			Recipe.newRecipe.requiredItem[0].Stack = 15;
			Recipe.newRecipe.requiredItem[1].SetDefaults(86);
			Recipe.newRecipe.requiredItem[1].Stack = 10;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Shadow Scalemail");
			Recipe.newRecipe.requiredItem[0].SetDefaults(57);
			Recipe.newRecipe.requiredItem[0].Stack = 25;
			Recipe.newRecipe.requiredItem[1].SetDefaults(86);
			Recipe.newRecipe.requiredItem[1].Stack = 20;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Shadow Greaves");
			Recipe.newRecipe.requiredItem[0].SetDefaults(57);
			Recipe.newRecipe.requiredItem[0].Stack = 20;
			Recipe.newRecipe.requiredItem[1].SetDefaults(86);
			Recipe.newRecipe.requiredItem[1].Stack = 15;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Nightmare Pickaxe");
			Recipe.newRecipe.requiredItem[0].SetDefaults(57);
			Recipe.newRecipe.requiredItem[0].Stack = 12;
			Recipe.newRecipe.requiredItem[1].SetDefaults(86);
			Recipe.newRecipe.requiredItem[1].Stack = 6;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("The Breaker");
			Recipe.newRecipe.requiredItem[0].SetDefaults(57);
			Recipe.newRecipe.requiredItem[0].Stack = 10;
			Recipe.newRecipe.requiredItem[1].SetDefaults(86);
			Recipe.newRecipe.requiredItem[1].Stack = 5;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Grappling Hook");
			Recipe.newRecipe.requiredItem[0].SetDefaults(85);
			Recipe.newRecipe.requiredItem[0].Stack = 3;
			Recipe.newRecipe.requiredItem[1].SetDefaults(118);
			Recipe.newRecipe.requiredItem[1].Stack = 1;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(117);
			Recipe.newRecipe.requiredItem[0].SetDefaults(116);
			Recipe.newRecipe.requiredItem[0].Stack = 6;
			Recipe.newRecipe.requiredTile[0] = 17;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(198);
			Recipe.newRecipe.requiredItem[0].SetDefaults(117);
			Recipe.newRecipe.requiredItem[0].Stack = 20;
			Recipe.newRecipe.requiredItem[1].SetDefaults(177);
			Recipe.newRecipe.requiredItem[1].Stack = 10;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(199);
			Recipe.newRecipe.requiredItem[0].SetDefaults(117);
			Recipe.newRecipe.requiredItem[0].Stack = 20;
			Recipe.newRecipe.requiredItem[1].SetDefaults(178);
			Recipe.newRecipe.requiredItem[1].Stack = 10;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(200);
			Recipe.newRecipe.requiredItem[0].SetDefaults(117);
			Recipe.newRecipe.requiredItem[0].Stack = 20;
			Recipe.newRecipe.requiredItem[1].SetDefaults(179);
			Recipe.newRecipe.requiredItem[1].Stack = 10;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(201);
			Recipe.newRecipe.requiredItem[0].SetDefaults(117);
			Recipe.newRecipe.requiredItem[0].Stack = 20;
			Recipe.newRecipe.requiredItem[1].SetDefaults(181);
			Recipe.newRecipe.requiredItem[1].Stack = 10;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(202);
			Recipe.newRecipe.requiredItem[0].SetDefaults(117);
			Recipe.newRecipe.requiredItem[0].Stack = 20;
			Recipe.newRecipe.requiredItem[1].SetDefaults(182);
			Recipe.newRecipe.requiredItem[1].Stack = 10;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(203);
			Recipe.newRecipe.requiredItem[0].SetDefaults(117);
			Recipe.newRecipe.requiredItem[0].Stack = 20;
			Recipe.newRecipe.requiredItem[1].SetDefaults(180);
			Recipe.newRecipe.requiredItem[1].Stack = 10;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(204);
			Recipe.newRecipe.requiredItem[0].SetDefaults(117);
			Recipe.newRecipe.requiredItem[0].Stack = 35;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(127);
			Recipe.newRecipe.requiredItem[0].SetDefaults(95);
			Recipe.newRecipe.requiredItem[1].SetDefaults(117);
			Recipe.newRecipe.requiredItem[1].Stack = 30;
			Recipe.newRecipe.requiredItem[2].SetDefaults(75);
			Recipe.newRecipe.requiredItem[2].Stack = 10;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(197);
			Recipe.newRecipe.requiredItem[0].SetDefaults(98);
			Recipe.newRecipe.requiredItem[1].SetDefaults(117);
			Recipe.newRecipe.requiredItem[1].Stack = 20;
			Recipe.newRecipe.requiredItem[2].SetDefaults(75);
			Recipe.newRecipe.requiredItem[2].Stack = 5;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Meteor Helmet");
			Recipe.newRecipe.requiredItem[0].SetDefaults(117);
			Recipe.newRecipe.requiredItem[0].Stack = 25;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Meteor Suit");
			Recipe.newRecipe.requiredItem[0].SetDefaults(117);
			Recipe.newRecipe.requiredItem[0].Stack = 35;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Meteor Leggings");
			Recipe.newRecipe.requiredItem[0].SetDefaults(117);
			Recipe.newRecipe.requiredItem[0].Stack = 30;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Meteor Shot");
			Recipe.newRecipe.createItem.Stack = 100;
			Recipe.newRecipe.requiredItem[0].SetDefaults(117);
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(151);
			Recipe.newRecipe.requiredItem[0].SetDefaults(154);
			Recipe.newRecipe.requiredItem[0].Stack = 25;
			Recipe.newRecipe.requiredItem[1].SetDefaults(150);
			Recipe.newRecipe.requiredItem[1].Stack = 40;
			Recipe.newRecipe.requiredTile[0] = 18;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(152);
			Recipe.newRecipe.requiredItem[0].SetDefaults(154);
			Recipe.newRecipe.requiredItem[0].Stack = 35;
			Recipe.newRecipe.requiredItem[1].SetDefaults(150);
			Recipe.newRecipe.requiredItem[1].Stack = 50;
			Recipe.newRecipe.requiredTile[0] = 18;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(153);
			Recipe.newRecipe.requiredItem[0].SetDefaults(154);
			Recipe.newRecipe.requiredItem[0].Stack = 30;
			Recipe.newRecipe.requiredItem[1].SetDefaults(150);
			Recipe.newRecipe.requiredItem[1].Stack = 45;
			Recipe.newRecipe.requiredTile[0] = 18;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(175);
			Recipe.newRecipe.requiredItem[0].SetDefaults(174);
			Recipe.newRecipe.requiredItem[0].Stack = 6;
			Recipe.newRecipe.requiredItem[1].SetDefaults(173);
			Recipe.newRecipe.requiredItem[1].Stack = 2;
			Recipe.newRecipe.requiredTile[0] = 77;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(119);
			Recipe.newRecipe.requiredItem[0].SetDefaults(175);
			Recipe.newRecipe.requiredItem[0].Stack = 15;
			Recipe.newRecipe.requiredItem[1].SetDefaults(55);
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(120);
			Recipe.newRecipe.requiredItem[0].SetDefaults(175);
			Recipe.newRecipe.requiredItem[0].Stack = 25;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(121);
			Recipe.newRecipe.requiredItem[0].SetDefaults(175);
			Recipe.newRecipe.requiredItem[0].Stack = 35;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(122);
			Recipe.newRecipe.requiredItem[0].SetDefaults(175);
			Recipe.newRecipe.requiredItem[0].Stack = 35;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(217);
			Recipe.newRecipe.requiredItem[0].SetDefaults(175);
			Recipe.newRecipe.requiredItem[0].Stack = 35;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(219);
			Recipe.newRecipe.requiredItem[0].SetDefaults(175);
			Recipe.newRecipe.requiredItem[0].Stack = 20;
			Recipe.newRecipe.requiredItem[1].SetDefaults("Handgun");
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(231);
			Recipe.newRecipe.requiredItem[0].SetDefaults(175);
			Recipe.newRecipe.requiredItem[0].Stack = 30;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(232);
			Recipe.newRecipe.requiredItem[0].SetDefaults(175);
			Recipe.newRecipe.requiredItem[0].Stack = 40;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(233);
			Recipe.newRecipe.requiredItem[0].SetDefaults(175);
			Recipe.newRecipe.requiredItem[0].Stack = 35;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(190);
			Recipe.newRecipe.requiredItem[0].SetDefaults("Silver Broadsword");
			Recipe.newRecipe.requiredItem[1].SetDefaults(208);
			Recipe.newRecipe.requiredItem[1].Stack = 40;
			Recipe.newRecipe.requiredItem[2].SetDefaults(209);
			Recipe.newRecipe.requiredItem[2].Stack = 20;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(191);
			Recipe.newRecipe.requiredItem[0].SetDefaults(208);
			Recipe.newRecipe.requiredItem[0].Stack = 40;
			Recipe.newRecipe.requiredItem[1].SetDefaults(209);
			Recipe.newRecipe.requiredItem[1].Stack = 30;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(185);
			Recipe.newRecipe.requiredItem[0].SetDefaults(84);
			Recipe.newRecipe.requiredItem[1].SetDefaults(208);
			Recipe.newRecipe.requiredItem[1].Stack = 30;
			Recipe.newRecipe.requiredItem[2].SetDefaults(210);
			Recipe.newRecipe.requiredItem[2].Stack = 3;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Depth Meter");
			Recipe.newRecipe.requiredItem[0].SetDefaults(20);
			Recipe.newRecipe.requiredItem[0].Stack = 10;
			Recipe.newRecipe.requiredItem[1].SetDefaults(21);
			Recipe.newRecipe.requiredItem[1].Stack = 8;
			Recipe.newRecipe.requiredItem[2].SetDefaults(19);
			Recipe.newRecipe.requiredItem[2].Stack = 6;
			Recipe.newRecipe.requiredTile[0] = 14;
			Recipe.newRecipe.requiredTile[1] = 15;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(193);
			Recipe.newRecipe.requiredItem[0].SetDefaults(173);
			Recipe.newRecipe.requiredItem[0].Stack = 20;
			Recipe.newRecipe.requiredTile[0] = 17;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Goggles");
			Recipe.newRecipe.requiredItem[0].SetDefaults(38);
			Recipe.newRecipe.requiredItem[0].Stack = 2;
			Recipe.newRecipe.requiredTile[0] = 18;
			Recipe.newRecipe.requiredTile[1] = 15;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Sunglasses");
			Recipe.newRecipe.requiredItem[0].SetDefaults("Black Lens");
			Recipe.newRecipe.requiredItem[0].Stack = 2;
			Recipe.newRecipe.requiredTile[0] = 18;
			Recipe.newRecipe.requiredTile[1] = 15;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Mana Crystal");
			Recipe.newRecipe.requiredItem[0].SetDefaults(75);
			Recipe.newRecipe.requiredItem[0].Stack = 10;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(43);
			Recipe.newRecipe.requiredItem[0].SetDefaults(38);
			Recipe.newRecipe.requiredItem[0].Stack = 10;
			Recipe.newRecipe.requiredTile[0] = 26;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(70);
			Recipe.newRecipe.requiredItem[0].SetDefaults(67);
			Recipe.newRecipe.requiredItem[0].Stack = 30;
			Recipe.newRecipe.requiredItem[1].SetDefaults(68);
			Recipe.newRecipe.requiredItem[1].Stack = 15;
			Recipe.newRecipe.requiredTile[0] = 26;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(71);
			Recipe.newRecipe.createItem.Stack = 100;
			Recipe.newRecipe.requiredItem[0].SetDefaults(72);
			Recipe.newRecipe.requiredItem[0].Stack = 1;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(72);
			Recipe.newRecipe.createItem.Stack = 1;
			Recipe.newRecipe.requiredItem[0].SetDefaults(71);
			Recipe.newRecipe.requiredItem[0].Stack = 100;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(72);
			Recipe.newRecipe.createItem.Stack = 100;
			Recipe.newRecipe.requiredItem[0].SetDefaults(73);
			Recipe.newRecipe.requiredItem[0].Stack = 1;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(73);
			Recipe.newRecipe.createItem.Stack = 1;
			Recipe.newRecipe.requiredItem[0].SetDefaults(72);
			Recipe.newRecipe.requiredItem[0].Stack = 100;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(73);
			Recipe.newRecipe.createItem.Stack = 100;
			Recipe.newRecipe.requiredItem[0].SetDefaults(74);
			Recipe.newRecipe.requiredItem[0].Stack = 1;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(74);
			Recipe.newRecipe.createItem.Stack = 1;
			Recipe.newRecipe.requiredItem[0].SetDefaults(73);
			Recipe.newRecipe.requiredItem[0].Stack = 100;
			Recipe.addRecipe();
		}

		private static void addRecipe()
		{
			Main.recipe[Recipe.numRecipes] = Recipe.newRecipe;
			Recipe.newRecipe = new Recipe();
			Recipe.numRecipes++;
		}
	}
}
